bitkeeper revision 1.1426.1.1 (4289cc8cPUM98bLJs4TV93NHY9LOKg)
Many files:
  Make interface to network/block scripts consistent:
  - output on stdout is returned to the script caller
  - output on stderr is logged at the error level, messages with a '-' prefix
    are logged at the debug level and messages with a '*' prefix are logged
    at the info level.
Signed-off-by: Christian Limpach <Christian.Limpach@cl.cam.ac.uk>

diff --git a/tools/examples/vif-bridge b/tools/examples/vif-bridge
--- a/tools/examples/vif-bridge
+++ b/tools/examples/vif-bridge
@@ -34,7 +34,7 @@
 # Exit if anything goes wrong
 set -e 
 
-echo "vif-bridge $*"
+echo "*vif-bridge $*" >&2
 
 # Operation name.
 OP=$1
@@ -63,8 +63,8 @@ case $OP in
         iptcmd='-D'
         ;;
     *)
-        echo 'Invalid command: ' $OP
-        echo 'Valid commands are: up, down'
+        echo 'Invalid command: ' $OP >&2
+        echo 'Valid commands are: up, down' >&2
         exit 1
         ;;
 esac
diff --git a/tools/examples/vif-nat b/tools/examples/vif-nat
--- a/tools/examples/vif-nat
+++ b/tools/examples/vif-nat
@@ -23,7 +23,7 @@
 # Exit if anything goes wrong
 set -e 
 
-echo "vif-nat $*"
+echo "*vif-nat $*" >&2
 
 # Operation name.
 OP=$1
@@ -56,8 +56,8 @@ case $OP in
         ipcmd='d'
         ;;
     *)
-        echo 'Invalid command: ' $OP
-        echo 'Valid commands are: up, down'
+        echo 'Invalid command: ' $OP >&2
+        echo 'Valid commands are: up, down' >&2
         exit 1
         ;;
 esac
