[TOOLS] A couple of check-script cleanups. Signed-off-by: Keir Fraser <keir@xensource.com>

diff --git a/tools/check/check_python_xml b/tools/check/check_python_xml
--- a/tools/check/check_python_xml
+++ b/tools/check/check_python_xml
@@ -1,11 +1,7 @@
 #!/bin/bash
 # CHECK-INSTALL
 
-function error {
-    echo
-    echo "  *** Check for python-xml package FAILED"
-    exit 1
-}
+RC=0
 
 python -c '
 import os.path, sys
@@ -13,4 +9,11 @@ for p in sys.path:
 	if os.path.exists(p + "/xml/dom/minidom.py"):
 		sys.exit(0)
 sys.exit(1)
-' || error
+' || RC=1
+
+if test ${RC} -ne 0; then
+    echo
+    echo "  *** Check for python-xml package FAILED"
+fi
+
+exit ${RC}
