This patch resizes the file system on the xm-test HVM disk.img to use the entire space available.
Signed-off-by: Daniel Stekloff <dsteklof@us.ibm.com>

diff --git a/tools/xm-test/ramdisk/bin/create_disk_image b/tools/xm-test/ramdisk/bin/create_disk_image
--- a/tools/xm-test/ramdisk/bin/create_disk_image
+++ b/tools/xm-test/ramdisk/bin/create_disk_image
@@ -208,6 +208,13 @@ function dd_rootfs_to_image()
 	if [ $? -ne 0 ]; then
 		die "Failed to dd $ROOTFS to $LOOPP."
 	fi
+
+	# Resize fs to use full partition
+	e2fsck -f $LOOPP 
+	resize2fs $LOOPP
+	if [ $? -ne 0 ]; then
+		die "Failed to resize rootfs on $LOOPP."
+	fi
 }
 
 function get_kernel()
